
const protectedPages = ['pyq.html', 'notes.html', 'upload-pyq.html', 'upload-notes.html', 'profile.html'];
const isProtected = protectedPages.some(p => window.location.pathname.includes(p));
const user = JSON.parse(localStorage.getItem('sau_user'));

if (isProtected && !user) {
    window.location.replace('auth.html');
}

document.addEventListener('DOMContentLoaded', function () {

    const loginLink = document.getElementById('login-link');
    if (loginLink && user) {
        loginLink.innerText = 'Profile';
        loginLink.href = 'profile.html';
    }

    const logoutBtn = document.getElementById('logout-btn');
    if (logoutBtn) {
        logoutBtn.addEventListener('click', function (e) {
            e.preventDefault();
            localStorage.removeItem('sau_user');
            window.location.href = 'index.html';
        });
    }
});



window.viewDocument = function(item, fallbackTitle) {
    if (item.files && item.files.length > 0) {
        const viewerWindow = window.open('', '_blank');
        let htmlStr = "<html><head><title>Viewing " + fallbackTitle + "</title><base href=\"" + window.location.href + "\"></head>";
        htmlStr += "<body style=\"text-align:center; background:#333; margin:0; padding:20px;\">";
        item.files.forEach(function(file) {
            if(file.toLowerCase().endsWith('.pdf')) {
                 htmlStr += "<iframe src=\"" + file + "\" style=\"width:100%; height:95vh; border:none;\"></iframe>";
            } else {
                 htmlStr += "<img src=\"" + file + "\" style=\"max-width:100%; margin-bottom: 20px; box-shadow: 0 0 10px #000; border: 3px solid #fff;\"><br>";
            }
        });
        htmlStr += "<" + "/body><" + "/html>";
        viewerWindow.document.write(htmlStr);
        viewerWindow.document.close();
    } else {
        const content = "Mock content for " + fallbackTitle + "\n\nThis file was generated by SAU Scholar Hub.";
        const blob = new Blob([content], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        window.open(url, '_blank');
    }
};

window.downloadDocument = function(item, fallbackTitle) {
    if (item.files && item.files.length > 0) {
        item.files.forEach((file, index) => {
            const a = document.createElement('a');
            a.style.display = 'none';
            a.href = file;
            a.download = fallbackTitle.replace(/\s+/g, '_') + (file.toLowerCase().endsWith('.pdf') ? '.pdf' : `_Part${index + 1}.jpeg`);
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
        });
    } else {
        const content = "Mock content for " + fallbackTitle + "\n\nThis file was generated by SAU Scholar Hub.";
        const blob = new Blob([content], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.style.display = 'none';
        a.href = url;
        a.download = fallbackTitle.replace(/\s+/g, '_') + '_Mock.txt';
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
    }
};

window.handleUpload = function(storageKey, newItem, fileInput, redirectUrl) {
    const btn = document.querySelector('button[type="submit"]');
    const msg = document.getElementById('success-msg');
    btn.innerText = 'Uploading...';
    btn.disabled = true;

    function finish(dataUrl) {
        newItem.files = dataUrl ? [dataUrl] : [];
        const customItems = JSON.parse(localStorage.getItem(storageKey) || '[]');
        customItems.push(newItem);
        try {
            localStorage.setItem(storageKey, JSON.stringify(customItems));
        } catch (err) {
            alert('File too large for local simulation. Saved as text only.');
            newItem.files = [];
            localStorage.setItem(storageKey, JSON.stringify(customItems));
        }
        msg.style.display = 'block';
        setTimeout(() => window.location.href = redirectUrl, 2000);
    }

    setTimeout(() => {
        if (fileInput.files && fileInput.files[0]) {
            const reader = new FileReader();
            reader.onload = e => finish(e.target.result);
            reader.readAsDataURL(fileInput.files[0]);
        } else {
            finish(null);
        }
    }, 1000);
};
